name: dotnet package

on: [push, release]

env:
  PROJECT_PATH: 'ShortSharp/src/ShortSharp/ShortSharp.csproj'
  PACKAGE_OUTPUT_DIRECTORY: '${{ github.workspace }}/output'
  NUGET_SRC_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: 'Setup dotnet ${{ matrix.dotnet-version }}'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: 'Display dotnet version'
        run: dotnet --version
        
      - name: 'Restore Package'
        run: dotnet restore ${{ env.PROJECT_PATH }}
        
      - name: 'Build Package'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
        
      - name: 'Pack Project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} --no-restore --configuration Release --no-build
        
      - name: 'Push to Nuget.org'
        run: |
            dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg 
            --source ${{ env.NUGET_SRC_URL }} 
            --api-key ${{ secrets.NUGET_ORG_API_KEY }} 
            --skip-duplicate
        
